---
functional:
  - Пользователь должен иметь возможность зарегестрироваться и войти в свой профиль
  - Пользователь должен иметь возможность редактировать профиль и менять пароль
  - Пользователь должен иметь возможность создать игру с необходимой конфигурацией и настройками
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен иметь возможность подключиться к игре повторно в случае форс-мажора
  - Пользователь должен видеть на экране информативный интерфейс с полем ввода, таймером, правилами и т.д.
  - Сайт должен самостоятельно компилировать и тестировать введенный пользователем код
  - Пользователь должен иметь возможность ознакомиться с результатом игры и получить общий фидбек
  - Сайт должен визуализировать нынешней положение в рейтинговой таблице
  - Сайт должен предоставлять доступ к истории сыгранных матчей
  - Сайт должен иметь чат для общения
  - Сайт должен обладать режимом игры с ботом для одиночной тренировки
  - Сайт должен иметь возможность организации турниров
  - Пользователь должен иметь возможность реализации собственных задач
non-functional:
  - Интерфейс сайта должен быть отзывчивым и корректно отображаться на разных устройствах
  - Система должна выдерживать наплыв большого количества пользователей и работать при высоких нагрузках
  - Данные пользователей должны храниться в зашифрованном виде
  - Взаимодействие должно проходить, через HTTPS протокол
  - Сайт должен корректно отображаться во всех версиях актуальных браузеров
  - Система должна логироваться для дальнейшего анализа и исправления ошибок
  - Система должна быть разработана с возможностью быстрых обновлений без простоев
  - Система должна быть разработана с возможностью мониторинга основных систем
implicit:
  - Пользователи ожидают от платформы частого и быстрого развития(новые режимы, ивенты, задачи)
  - Пользователи должны быть уверены в сохранение рейтинговых данных
  - Уровни сложности должны соответствовать реальному уровню
  - Пользователи должны быть уверены в равенстве условий при прохождении заданий
  - Пользователи ожидают стабильную работу сервиса
  - Пользователи должны иметь возможность переподключения и сохранения прогресса незавершенных задач
