---
functional:
  - Пользователь должен иметь возможность зарегистрировать учетную запись на сайте
  - Пользователь должен иметь войти под зарегистрированной на сайте учетной записью
  - Пользователь должен иметь возможность войти под учетной записью GitHub
  - Пользователь должен иметь возможность войти под учетной записью Discord
  - Пользователь должен иметь возможность редактировать профиль и менять пароль
  - Пользователь должен иметь возможность создать игру с необходимой сложностью
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен иметь возможность подключиться к игре повторно
  - Пользователь должен иметь возможность создавать игру пройдя на стартовую страницу сайта
  - Пользователь должен иметь возможность при создании матча добавлять конкретных пользователей для игры и случайных игроков
  - Система должна определять победителя выполнившего большее количество задач или первым выполнившим все задачи
  - Пользователю должен быть доступен просмотр чужого матча
  - Сайт должен предоставлять пользователю возможность настройки профиля, оформление сайта,удобный доступ к истории задач и кланам
  - Пользователь должен иметь возможность смены языка программирования в Editor,так же возможность менять язык в зависимости от задачи
  - Сайт должен самостоятельно компилировать и тестировать введенный пользователем код
  - Пользователь должен иметь возможность ознакомиться с результатом игры
  - Сайт должен визуализировать нынешней положение в рейтинговой таблице
  - Сайт должен предоставлять доступ к истории сыгранных матчей
  - Сайт должен иметь чат для общения
  - Сайт должен обладать режимом игры с ботом для одиночной тренировки
  - Сайт должен иметь возможность организации турниров
  - Пользователь должен иметь возможность загружать собственные задачи для всех пользователей платформы
non-functional:
  - Интерфейс сайта должен быть отзывчивым и корректно отображаться на разных устройствах
  - Система должна выдерживать наплыв большого количества пользователей и работать при высоких нагрузках
  - Данные пользователей должны храниться в зашифрованном виде
  - Взаимодействие должно проходить, через HTTPS протокол
  - Сайт должен корректно отображаться во всех версиях актуальных браузеров
  - Система должна логироваться для дальнейшего анализа и исправления ошибок
  - Система должна быть разработана с возможностью быстрых обновлений без простоев
  - Система должна быть разработана с возможностью мониторинга основных систем
  - Пользователь должен видеть на экране информативный интерфейс с полем ввода, таймером, правилами и т.д.
implicit:
  - Пользователи ожидают от платформы частого и быстрого развития(новые режимы, ивенты, задачи)
  - Пользователи должны быть уверены в сохранение рейтинговых данных
  - Уровни сложности должны соответствовать реальному уровню
  - Пользователи должны быть уверены в равенстве условий при прохождении заданий
  - Пользователи ожидают стабильную работу сервиса
  - Пользователи должны иметь возможность переподключения и сохранения прогресса незавершенных задач
  - Сайт должен поддерживать кроссбраузерность
